monolog:
    channels: ['saml']
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: info
        saml:
            type: stream
            path: '%kernel.logs_dir%/saml.log'
            level: debug
            channels: ['saml']
