<?php

namespace App\Repository;

/**
 * IdPUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdPUserRepository extends \Doctrine\ORM\EntityRepository
{
    public function countByIdp($idp): int
    {
        $qb = $this->createQueryBuilder('a');
        $qb->select('COUNT(a)')
           ->where('a.IdP = :idp')
           ->setParameter('idp', $idp);
        return (int) $qb->getQuery()->getSingleScalarResult();
    }
}
